### ISSUE TITLE
Fixed position bottom styling makes bar invisible

### ISSUE THREAD

**Issue by jh3y** [jh3y/ep#26]
## Issue summary
When the bar is `fixed-bottom` in the demo, it disappears.

## Expected behavior
Should see it fixed to the bottom of the page.

## Browser used
Any.

## Steps to reproduce
Check the demo, and change the positional demo to `fixed-bottom`.

## Resolution
Instead of setting to `bottom: 0`, the bar position should be set to `bottom: 6px` or whatever the height of the bar is.

@jh3y

**Comment by whoffmann** [comment]
Hey, I can't reproduce this in the demo on Chrome 54. The bar is set to `bottom: 0` and it looks fine. Are there any other factors in reproducing this?

![image](https://cloud.githubusercontent.com/assets/2459843/19583961/c4d5aad2-970e-11e6-8713-0cf70bb81b2b.png)

**Comment by jh3y** [comment]
Hey @whoffmann 

I think you're right actually. I've just rechecked this and it seems to be working now. It must've just played up on me for a second 😕 

Thanks for this 👍 

@jh3y
