### ISSUE TITLE
Please include  dist...

### ISSUE THREAD

**Issue by luncht1me** [jh3y/ep#32]
Having to go into the ep folder after downloading it, and manually npm installing, and running `make dist` is a pain in the ass...

Not to mention, building needs additional configuration, as the Class EP element can't be converted to javascript properly out of the box (not using webpack, just bower / npm / node). 

I had to make another .babelrc file with the following contents:
```
{
	"presets": ["es2015"]
}
```
in order to get `make dist-script` to work.

So please, for the love of god, for those who aren't using your exact development environment, or don't have any knowledge of debugging this kind of thing... please either include dist files of the latest build, or at the very least also include a `.babelrc` file so that `make` works without a webpack compiler.

**Comment by jh3y** [comment]
Hi @luncht1me 👋 

No need for that tone 😄  I do understand the benefits of including `dist`. In fact, up until recently it was included with the source. #27 removed it on the premise that it would be coming through as part of the install and generated prepublish. I can confirm this is the case after installing version `2.0.5` with both `npm` and `yarn` locally. `node_modules/@jh3y/ep/dist` exists in both cases including both minified and unminified versions of the `css` and `js`.

Hope that helps!

@jh3y

**Comment by luncht1me** [comment]
Yeah, it didn't build for me. I had to reconfigure things and manually
compile. The npm scripts didn't work out of the box on my setup :P can give
more details some other time. It's more for noobie's benefit. I'll try it
again from fresh and reconfirm.

It was thru bower it failed

**Comment by jh3y** [comment]
Hey @luncht1me 

Ahh right. For sure, once everything is installed, then the different tasks to build can be ran.

I hadn't tried with `bower` but after testing with `bower`, I can confirm that `dist` is not present. Good spot! 👍  I'm wondering if there is a way to resolve this or if it's just easier to add those sources back into vc.

@jh3y

**Comment by jh3y** [comment]
It seems there is likely a way to do this from looking at [this](https://github.com/chartjs/Chart.js/issues/3033) issue thread 👍

**Comment by jh3y** [comment]
Closing as now `bower` even suggest migrating away from usage:
```
...psst! While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects read how to migrate!
```
